# Generated by Django 5.1.4 on 2024-12-15 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction_name', models.CharField(max_length=10)),
                ('line_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MRT.line')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=10)),
                ('line_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MRT.line')),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_number', models.IntegerField()),
                ('day_type', models.CharField(max_length=10)),
                ('direction_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MRT.direction')),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.TimeField()),
                ('station_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MRT.station')),
                ('train_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MRT.train')),
            ],
        ),
    ]
