# Generated by Django 5.1.4 on 2024-12-15 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MRT', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='line_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='MRT.line'),
        ),
    ]
