# Generated by Django 5.1.4 on 2024-12-15 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MRT', '0002_alter_direction_line_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='line_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='MRT.line'),
        ),
    ]
