# Generated by Django 3.2.24 on 2024-12-24 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MRT', '0003_alter_station_line_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='train_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='MRT.train'),
        ),
        migrations.AlterField(
            model_name='train',
            name='direction_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trains', to='MRT.direction'),
        ),
    ]
