# Generated by Django 3.2 on 2024-12-21 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_predict', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockindex',
            old_name='date',
            new_name='Date',
        ),
    ]
