# Generated by Django 3.2 on 2024-12-21 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_predict', '0002_rename_date_stockindex_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockindex',
            name='Score_Score_Comprehensive',
            field=models.FloatField(default=0),
        ),
    ]
