# Generated by Django 3.2 on 2024-12-21 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_predict', '0003_stockindex_score_score_comprehensive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockindex',
            old_name='Score_Score_Comprehensive',
            new_name='Score_Comprehensive',
        ),
    ]
