# Generated by Django 3.2 on 2024-12-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_predict', '0004_rename_score_score_comprehensive_stockindex_score_comprehensive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockindex',
            name='Date',
            field=models.DateField(),
        ),
    ]
