# Generated by Django 3.2 on 2024-12-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_predict', '0005_alter_stockindex_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockindex',
            name='Date',
            field=models.CharField(max_length=30),
        ),
    ]
