# Generated by Django 3.2.24 on 2024-12-24 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_predict', '0006_alter_stockindex_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockindex',
            unique_together={('company', 'Date')},
        ),
    ]
